spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mezmur
    username: mezmur
    password: mezmur
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa.show-sql: false
  jpa.hibernate.ddl-auto: create